"""add_user_id

Revision ID: f19e8b80c013
Revises: 0001_initial
Create Date: 2026-06-15 20:24:32.773287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19e8b80c013'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('user_id', sa.Text(), server_default='admin', nullable=False))
    op.create_index('idx_files_user_active', 'files', ['user_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.add_column('folders', sa.Column('user_id', sa.Text(), server_default='admin', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folders', 'user_id')
    op.drop_index('idx_files_user_active', table_name='files', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_column('files', 'user_id')
    # ### end Alembic commands ###
